### ISSUE TITLE
last-of-type float right?

### ISSUE THREAD

**Issue by matthewmueller** [dope/lemonade#12]
Any reason for:

``` css
/* Floats last ".bit-" to the right */
[class*='bit-']:last-of-type {
  float: right;
}
```

?

It seems like left/centering would be better.
