### ISSUE TITLE
Floats don't clear properly under certain media queries

### ISSUE THREAD

**Issue by matthewmueller** [dope/lemonade#21]
Here's an example: http://jsbin.com/sabuqowota/2/edit?html,css,output

To fix this issue, you can do something like:

``` css
@media (min-width: 50em) and (max-width: 68.75em) {
  .bit-4:nth-child(3n) {
    clear: left;
  }
}

@media (min-width: 30em) and (max-width: 50em) {
  .bit-4:nth-child(3n) {
    clear: left;
  }
}
```

But this would need to be generalized for all the other media-queries and bits.
